buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.2'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
        maven { url "https://oss.sonatype.org/content/repositories/releases/"  }
    }
}

ext {
    gdxVersion              = '1.12.1'
    androidMinSdkVersion    = 21
    androidTargetSdkVersion = 34
    androidCompileSdkVersion= 34
}
